server:
  port: 8781

spring:
  redis:
    host: 192.168.2.2
    port: 6379
    database: 0
    timeout: 2000
  zipkin:
    base-url: http://192.168.2.2:9411/

PRODUCT-SERVICE:  #服务提供者服务名
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

#修改调用超时时间
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 1000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000 # 熔断超时时长：6000ms
        timeout:
          enable: true
management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  rabbitmq:
    host: 192.168.2.2
    port: 5672
    username: guest
    password: guest

